all: ConfigurationSettings.cpp Logger.cpp OperatingSystem.cpp PhaseOne.cpp ProcessControlBlock.cpp SimpleTimer.cpp
	g++ -std=c++11 -Wall -g ConfigurationSettings.cpp Logger.cpp OperatingSystem.cpp PhaseOne.cpp ProcessControlBlock.cpp SimpleTimer.cpp -o PhaseOne -lre2
